SET IDENTITY_INSERT [dbo].[Natives] ON
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (1, N'pennywort', N'Used as a culinary vegetable and as a medicinal herb', N'', N'Centella asiatica', N'Insignificant', N'Sand,Loam,Clay', N'Aquatic and Riparian Zone Plants')
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (2, N'angled lobelia', N'Help stabilize the sediment which can increase water clarity ', N'', N'Lobelia anceps syn: alata', N'Purple', N'Loam,Clay', N'')
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (3, N'nardoo', N'Form dense swards following flooding so that it is the dominant component of the groundcover layer', N'', N'Marsilea drummondii', N'Insignificant', N'Sand,Loam,Clay', N'Aquatic and Riparian Zone Plants')
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (4, N'swamp mazus', N'A native ground cover for wet to waterlogged soils', N'', N'Mazus pumilio', N'Purple', N'Sand,Loam,Clay', N'Aquatic and Riparian Zone Plants')
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (5, N'creeping monkey flower', N'Provide important living space for small animals such as aquatic insects and snails ', N'', N'Mimulus repens', N'Purple', N'Sand,Loam,Clay', N'Aquatic and Riparian Zone Plants')
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (6, N'slender knotweed', N'Soak up pollutants from contaminated water ', N'', N'Persicaria decipiens', N'Pink', N'Sand,Loam,Clay', N'Aquatic and Riparian Zone Plants')
INSERT INTO [dbo].[Natives] ([Id], [Name], [Description], [ImageUrl], [BotanicalName], [Colour], [SoilTexture], [Type]) VALUES (7, N'vanilla lily', N'Useful for hedging and screening or as a topiary specimen.', N'', N'Arthropodium strictum', N'Purple', N'Sand,Loam,Clay', N'Aquatic and Riparian Zone Plants')
SET IDENTITY_INSERT [dbo].[Natives] OFF
